# Generated by Django 2.1.1 on 2018-09-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='names',
        ),
    ]
